"""Add ai_risk_state table for autonomous drawdown control

Revision ID: 07f81b1ad229
Revises: 014_ai_week7
Create Date: 2025-12-26 12:36:09.527310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07f81b1ad229'
down_revision: Union[str, Sequence[str], None] = '014_ai_week7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_risk_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('previous_state', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('current_drawdown', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('NORMAL', 'DEGRADED', 'PAUSED')", name='chk_state_valid'),
    sa.CheckConstraint('consecutive_losses >= 0', name='chk_consecutive_losses_non_negative'),
    sa.CheckConstraint('current_drawdown >= 0 AND current_drawdown <= 100', name='chk_drawdown_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_id', name='uq_ai_risk_state_user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_risk_state')
    # ### end Alembic commands ###
