"""Add market data abstraction tables and broker support

Revision ID: 30e8151f97fd
Revises: 48f5e325b300
Create Date: 2026-01-14 23:58:29.757714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e8151f97fd'
down_revision: Union[str, Sequence[str], None] = '48f5e325b300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_instrument_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('canonical_symbol', sa.String(length=50), nullable=False),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('broker_symbol', sa.String(length=100), nullable=False),
    sa.Column('broker_token', sa.BigInteger(), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('underlying', sa.String(length=20), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_symbol', 'broker', name='uq_symbol_broker')
    )
    op.create_index('idx_broker_symbol', 'broker_instrument_tokens', ['broker', 'broker_symbol'], unique=False)
    op.create_index('idx_broker_token', 'broker_instrument_tokens', ['broker', 'broker_token'], unique=False)
    op.create_index('idx_canonical_symbol', 'broker_instrument_tokens', ['canonical_symbol'], unique=False)
    op.create_index('idx_expiry', 'broker_instrument_tokens', ['expiry'], unique=False)
    op.create_index(op.f('ix_broker_instrument_tokens_broker'), 'broker_instrument_tokens', ['broker'], unique=False)
    op.create_index(op.f('ix_broker_instrument_tokens_canonical_symbol'), 'broker_instrument_tokens', ['canonical_symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_instrument_tokens_canonical_symbol'), table_name='broker_instrument_tokens')
    op.drop_index(op.f('ix_broker_instrument_tokens_broker'), table_name='broker_instrument_tokens')
    op.drop_index('idx_expiry', table_name='broker_instrument_tokens')
    op.drop_index('idx_canonical_symbol', table_name='broker_instrument_tokens')
    op.drop_index('idx_broker_token', table_name='broker_instrument_tokens')
    op.drop_index('idx_broker_symbol', table_name='broker_instrument_tokens')
    op.drop_table('broker_instrument_tokens')
    # ### end Alembic commands ###
