"""add_regime_conditioned_decision_quality_priority_2_2

Revision ID: 3e53c2250f8a
Revises: 9ed66e62a8fe
Create Date: 2025-12-26 15:45:03.803866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e53c2250f8a'
down_revision: Union[str, Sequence[str], None] = '9ed66e62a8fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_regime_performance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('regime_type', sa.String(length=30), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('avg_pnl_per_trade', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_win', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_loss', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('avg_overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_pnl_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_entry_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_adjustment_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_exit_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('normalized_overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('normalized_pnl_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('normalized_risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_minutes_in_regime', sa.Integer(), nullable=False),
    sa.Column('regime_prevalence_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('avg_adjustment_score >= 0 AND avg_adjustment_score <= 100', name='chk_regime_perf_avg_adjustment_score_range'),
    sa.CheckConstraint('avg_entry_score >= 0 AND avg_entry_score <= 100', name='chk_regime_perf_avg_entry_score_range'),
    sa.CheckConstraint('avg_exit_score >= 0 AND avg_exit_score <= 100', name='chk_regime_perf_avg_exit_score_range'),
    sa.CheckConstraint('avg_overall_score >= 0 AND avg_overall_score <= 100', name='chk_regime_perf_avg_overall_score_range'),
    sa.CheckConstraint('avg_pnl_score >= 0 AND avg_pnl_score <= 100', name='chk_regime_perf_avg_pnl_score_range'),
    sa.CheckConstraint('avg_risk_score >= 0 AND avg_risk_score <= 100', name='chk_regime_perf_avg_risk_score_range'),
    sa.CheckConstraint('losing_trades >= 0', name='chk_regime_perf_losing_trades_non_negative'),
    sa.CheckConstraint('regime_prevalence_pct >= 0 AND regime_prevalence_pct <= 100', name='chk_regime_perf_prevalence_range'),
    sa.CheckConstraint('total_minutes_in_regime >= 0', name='chk_regime_perf_total_minutes_non_negative'),
    sa.CheckConstraint('total_trades >= 0', name='chk_regime_perf_total_trades_non_negative'),
    sa.CheckConstraint('win_rate >= 0 AND win_rate <= 100', name='chk_regime_perf_win_rate_range'),
    sa.CheckConstraint('winning_trades >= 0', name='chk_regime_perf_winning_trades_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'report_date', 'regime_type', name='uq_ai_regime_performance_user_date_regime')
    )
    op.create_index(op.f('ix_ai_regime_performance_regime_type'), 'ai_regime_performance', ['regime_type'], unique=False)
    op.create_index(op.f('ix_ai_regime_performance_report_date'), 'ai_regime_performance', ['report_date'], unique=False)
    op.create_index(op.f('ix_ai_regime_performance_user_id'), 'ai_regime_performance', ['user_id'], unique=False)
    op.add_column('ai_learning_reports', sa.Column('regime_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('ai_learning_reports', sa.Column('dominant_regime', sa.String(length=30), nullable=True))
    op.add_column('ai_learning_reports', sa.Column('dominant_regime_pct', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_learning_reports', 'dominant_regime_pct')
    op.drop_column('ai_learning_reports', 'dominant_regime')
    op.drop_column('ai_learning_reports', 'regime_breakdown')
    op.drop_index(op.f('ix_ai_regime_performance_user_id'), table_name='ai_regime_performance')
    op.drop_index(op.f('ix_ai_regime_performance_report_date'), table_name='ai_regime_performance')
    op.drop_index(op.f('ix_ai_regime_performance_regime_type'), table_name='ai_regime_performance')
    op.drop_table('ai_regime_performance')
    # ### end Alembic commands ###
