"""add_smartapi_support

Revision ID: 48f5e325b300
Revises: 5c8d7032e2b4
Create Date: 2026-01-03 12:18:48.424524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f5e325b300'
down_revision: Union[str, Sequence[str], None] = '5c8d7032e2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smartapi_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(length=20), nullable=False),
    sa.Column('encrypted_pin', sa.Text(), nullable=False),
    sa.Column('encrypted_totp_secret', sa.Text(), nullable=False),
    sa.Column('jwt_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('feed_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_auth_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smartapi_credentials_user_id'), 'smartapi_credentials', ['user_id'], unique=True)
    op.add_column('user_preferences', sa.Column('market_data_source', sa.String(length=20), server_default='smartapi', nullable=False))
    op.create_check_constraint('check_market_data_source', 'user_preferences', "market_data_source IN ('smartapi', 'kite')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_market_data_source', 'user_preferences')
    op.drop_column('user_preferences', 'market_data_source')
    op.drop_index(op.f('ix_smartapi_credentials_user_id'), table_name='smartapi_credentials')
    op.drop_table('smartapi_credentials')
    # ### end Alembic commands ###
