"""add_ai_paper_trades_table

Revision ID: 5c8d7032e2b4
Revises: 4fdaa5624e7d
Create Date: 2025-12-29 14:15:05.152549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c8d7032e2b4'
down_revision: Union[str, Sequence[str], None] = '4fdaa5624e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_paper_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('underlying', sa.String(length=20), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entry_regime', sa.String(length=30), nullable=False),
    sa.Column('entry_confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sizing_mode', sa.String(length=20), nullable=False),
    sa.Column('lots', sa.Integer(), nullable=False),
    sa.Column('legs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('entry_total_premium', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exit_total_premium', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sizing_mode IN ('fixed', 'tiered', 'kelly')", name='chk_ai_paper_trades_sizing_mode_valid'),
    sa.CheckConstraint("status IN ('open', 'closed')", name='chk_ai_paper_trades_status_valid'),
    sa.CheckConstraint('entry_confidence >= 0 AND entry_confidence <= 100', name='chk_ai_paper_trades_confidence_range'),
    sa.CheckConstraint('lots > 0', name='chk_ai_paper_trades_lots_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_paper_trades_entry_time', 'ai_paper_trades', ['entry_time'], unique=False)
    op.create_index('idx_ai_paper_trades_status', 'ai_paper_trades', ['status'], unique=False)
    op.create_index('idx_ai_paper_trades_user_id', 'ai_paper_trades', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ai_paper_trades_user_id', table_name='ai_paper_trades')
    op.drop_index('idx_ai_paper_trades_status', table_name='ai_paper_trades')
    op.drop_index('idx_ai_paper_trades_entry_time', table_name='ai_paper_trades')
    op.drop_table('ai_paper_trades')
    # ### end Alembic commands ###
