"""Add ai_strategy_cooldown table for strategy kill memory

Revision ID: 854fcf898768
Revises: 07f81b1ad229
Create Date: 2025-12-26 12:44:45.085877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '854fcf898768'
down_revision: Union[str, Sequence[str], None] = '07f81b1ad229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_strategy_cooldown',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_name', sa.String(length=50), nullable=False),
    sa.Column('regime_type', sa.String(length=30), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('total_loss', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('failure_count > 0', name='chk_failure_count_positive'),
    sa.CheckConstraint('total_loss >= 0', name='chk_total_loss_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'strategy_name', 'regime_type', name='uq_ai_strategy_cooldown_user_strategy_regime')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_strategy_cooldown')
    # ### end Alembic commands ###
