"""add_global_personalized_ml_blending_priority_2_1

Revision ID: 9ed66e62a8fe
Revises: eba6d4e94406
Create Date: 2025-12-26 15:29:26.606290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed66e62a8fe'
down_revision: Union[str, Sequence[str], None] = 'eba6d4e94406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add ai_model_registry columns (scope nullable first, then set defaults, then make NOT NULL)
    op.add_column('ai_model_registry', sa.Column('scope', sa.String(length=10), nullable=True))
    op.add_column('ai_model_registry', sa.Column('user_id', sa.UUID(), nullable=True))

    # Set default scope='user' for existing rows
    op.execute("UPDATE ai_model_registry SET scope = 'user' WHERE scope IS NULL")

    # Now make scope NOT NULL
    op.alter_column('ai_model_registry', 'scope', nullable=False)

    # Drop old unique constraint and create new partial indexes
    op.drop_constraint(op.f('uq_ai_model_registry_version'), 'ai_model_registry', type_='unique')
    op.create_index('idx_ai_model_registry_global_version', 'ai_model_registry', ['version'], unique=True, postgresql_where=sa.text("scope = 'global'"))
    op.create_index('idx_ai_model_registry_user_version', 'ai_model_registry', ['version', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_foreign_key(None, 'ai_model_registry', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # Add ai_user_config columns (nullable first, then set defaults, then make NOT NULL)
    op.add_column('ai_user_config', sa.Column('enable_ml_blending', sa.Boolean(), nullable=True))
    op.add_column('ai_user_config', sa.Column('blending_alpha_start', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('ai_user_config', sa.Column('blending_alpha_min', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('ai_user_config', sa.Column('blending_trades_threshold', sa.Integer(), nullable=True))
    op.add_column('ai_user_config', sa.Column('total_trades_completed', sa.Integer(), nullable=True))

    # Set defaults for existing rows
    op.execute("UPDATE ai_user_config SET enable_ml_blending = TRUE WHERE enable_ml_blending IS NULL")
    op.execute("UPDATE ai_user_config SET blending_alpha_start = 1.00 WHERE blending_alpha_start IS NULL")
    op.execute("UPDATE ai_user_config SET blending_alpha_min = 0.20 WHERE blending_alpha_min IS NULL")
    op.execute("UPDATE ai_user_config SET blending_trades_threshold = 100 WHERE blending_trades_threshold IS NULL")
    op.execute("UPDATE ai_user_config SET total_trades_completed = 0 WHERE total_trades_completed IS NULL")

    # Now make columns NOT NULL
    op.alter_column('ai_user_config', 'enable_ml_blending', nullable=False)
    op.alter_column('ai_user_config', 'blending_alpha_start', nullable=False)
    op.alter_column('ai_user_config', 'blending_alpha_min', nullable=False)
    op.alter_column('ai_user_config', 'blending_trades_threshold', nullable=False)
    op.alter_column('ai_user_config', 'total_trades_completed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_user_config', 'total_trades_completed')
    op.drop_column('ai_user_config', 'blending_trades_threshold')
    op.drop_column('ai_user_config', 'blending_alpha_min')
    op.drop_column('ai_user_config', 'blending_alpha_start')
    op.drop_column('ai_user_config', 'enable_ml_blending')
    op.drop_constraint(None, 'ai_model_registry', type_='foreignkey')
    op.drop_index('idx_ai_model_registry_user_version', table_name='ai_model_registry', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('idx_ai_model_registry_global_version', table_name='ai_model_registry', postgresql_where=sa.text("scope = 'global'"))
    op.create_unique_constraint(op.f('uq_ai_model_registry_version'), 'ai_model_registry', ['version'], postgresql_nulls_not_distinct=False)
    op.drop_column('ai_model_registry', 'user_id')
    op.drop_column('ai_model_registry', 'scope')
    # ### end Alembic commands ###
