"""add broker_api_credentials unified table

Revision ID: c14bb31eee95
Revises: 41cd324abe51
Create Date: 2026-03-20 12:23:43.090380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c14bb31eee95'
down_revision: Union[str, Sequence[str], None] = '41cd324abe51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_api_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('api_secret', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(length=100), nullable=True),
    sa.Column('encrypted_pin', sa.Text(), nullable=True),
    sa.Column('encrypted_totp_secret', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('feed_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_auth_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('broker_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'broker', name='uq_broker_api_credentials_user_broker')
    )
    op.create_index(op.f('ix_broker_api_credentials_broker'), 'broker_api_credentials', ['broker'], unique=False)
    op.create_index(op.f('ix_broker_api_credentials_user_id'), 'broker_api_credentials', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Data migration: copy smartapi_credentials into broker_api_credentials
    op.execute("""
        INSERT INTO broker_api_credentials (
            id, user_id, broker, client_id, encrypted_pin, encrypted_totp_secret,
            access_token, feed_token, refresh_token, token_expiry,
            is_active, last_auth_at, last_error, created_at, updated_at
        )
        SELECT
            gen_random_uuid(), user_id, 'angelone', client_id, encrypted_pin, encrypted_totp_secret,
            jwt_token, feed_token, refresh_token, token_expiry,
            is_active, last_auth_at, last_error, created_at, updated_at
        FROM smartapi_credentials
        ON CONFLICT (user_id, broker) DO NOTHING
    """)

    # Data migration: copy zerodha_credentials
    op.execute("""
        INSERT INTO broker_api_credentials (
            id, user_id, broker, api_key, api_secret,
            is_active, last_error, created_at, updated_at
        )
        SELECT
            gen_random_uuid(), user_id, 'zerodha', api_key, encrypted_api_secret,
            is_active, last_error, created_at, updated_at
        FROM zerodha_credentials
        ON CONFLICT (user_id, broker) DO NOTHING
    """)

    # Data migration: copy upstox_credentials
    op.execute("""
        INSERT INTO broker_api_credentials (
            id, user_id, broker, api_key, api_secret,
            is_active, last_error, created_at, updated_at
        )
        SELECT
            gen_random_uuid(), user_id, 'upstox', api_key, encrypted_api_secret,
            is_active, last_error, created_at, updated_at
        FROM upstox_credentials
        ON CONFLICT (user_id, broker) DO NOTHING
    """)

    # Data migration: copy dhan_credentials
    op.execute("""
        INSERT INTO broker_api_credentials (
            id, user_id, broker, client_id, access_token,
            is_active, last_auth_at, last_error, created_at, updated_at
        )
        SELECT
            gen_random_uuid(), user_id, 'dhan', client_id, encrypted_access_token,
            is_active, last_auth_at, last_error, created_at, updated_at
        FROM dhan_credentials
        ON CONFLICT (user_id, broker) DO NOTHING
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_api_credentials_user_id'), table_name='broker_api_credentials')
    op.drop_index(op.f('ix_broker_api_credentials_broker'), table_name='broker_api_credentials')
    op.drop_table('broker_api_credentials')
    # ### end Alembic commands ###
