"""add user_preferences table

Revision ID: c16511af0abe
Revises: c79149025c75
Create Date: 2025-12-21 14:38:00.099551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c16511af0abe'
down_revision: Union[str, Sequence[str], None] = 'c79149025c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pnl_grid_interval', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('pnl_grid_interval IN (50, 100)', name='check_pnl_grid_interval'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_index(op.f('idx_adjustment_logs_rule'), table_name='autopilot_adjustment_logs')
    op.drop_index(op.f('idx_adjustment_logs_strategy'), table_name='autopilot_adjustment_logs')
    op.drop_index(op.f('idx_adjustment_logs_triggered'), table_name='autopilot_adjustment_logs')
    op.drop_index(op.f('idx_adjustment_logs_user'), table_name='autopilot_adjustment_logs')
    op.alter_column('autopilot_adjustment_suggestions', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='Adjustment category: defensive (reduces risk), offensive (increases risk for premium), neutral (rebalances)',
               existing_server_default=sa.text("'defensive'::character varying"))
    op.drop_index(op.f('idx_analytics_cache_key'), table_name='autopilot_analytics_cache')
    op.drop_index(op.f('idx_analytics_cache_user'), table_name='autopilot_analytics_cache')
    op.drop_index(op.f('idx_analytics_cache_valid'), table_name='autopilot_analytics_cache')
    op.drop_index(op.f('idx_backtests_created'), table_name='autopilot_backtests')
    op.drop_index(op.f('idx_backtests_status'), table_name='autopilot_backtests')
    op.drop_index(op.f('idx_backtests_user'), table_name='autopilot_backtests')
    op.drop_index(op.f('idx_autopilot_condition_eval_latest'), table_name='autopilot_condition_eval')
    op.drop_index(op.f('idx_autopilot_condition_eval_strategy'), table_name='autopilot_condition_eval')
    op.drop_index(op.f('idx_autopilot_condition_eval_time'), table_name='autopilot_condition_eval')
    op.drop_index(op.f('idx_autopilot_daily_summary_date'), table_name='autopilot_daily_summary')
    op.drop_index(op.f('idx_autopilot_daily_summary_user'), table_name='autopilot_daily_summary')
    op.drop_index(op.f('idx_autopilot_daily_summary_user_date'), table_name='autopilot_daily_summary')
    op.drop_index(op.f('idx_autopilot_logs_created'), table_name='autopilot_logs')
    op.drop_index(op.f('idx_autopilot_logs_data'), table_name='autopilot_logs', postgresql_ops={'event_data': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_autopilot_logs_event'), table_name='autopilot_logs')
    op.drop_index(op.f('idx_autopilot_logs_recent'), table_name='autopilot_logs')
    op.drop_index(op.f('idx_autopilot_logs_severity'), table_name='autopilot_logs', postgresql_where="(severity = ANY (ARRAY['error'::autopilot_log_severity, 'critical'::autopilot_log_severity]))")
    op.drop_index(op.f('idx_autopilot_logs_strategy'), table_name='autopilot_logs', postgresql_where='(strategy_id IS NOT NULL)')
    op.drop_index(op.f('idx_autopilot_logs_user'), table_name='autopilot_logs')
    op.drop_index(op.f('idx_autopilot_logs_user_created'), table_name='autopilot_logs')
    op.drop_index(op.f('idx_order_batches_created'), table_name='autopilot_order_batches')
    op.drop_index(op.f('idx_order_batches_strategy'), table_name='autopilot_order_batches')
    op.drop_index(op.f('idx_order_batches_trading_mode'), table_name='autopilot_order_batches')
    op.drop_index(op.f('idx_order_batches_user'), table_name='autopilot_order_batches')
    op.drop_index(op.f('idx_autopilot_orders_batch_id'), table_name='autopilot_orders')
    op.drop_index(op.f('idx_autopilot_orders_created'), table_name='autopilot_orders')
    op.drop_index(op.f('idx_autopilot_orders_kite'), table_name='autopilot_orders', postgresql_where='(kite_order_id IS NOT NULL)')
    op.drop_index(op.f('idx_autopilot_orders_pending'), table_name='autopilot_orders', postgresql_where="(status = ANY (ARRAY['pending'::autopilot_order_status, 'placed'::autopilot_order_status, 'open'::autopilot_order_status]))")
    op.drop_index(op.f('idx_autopilot_orders_status'), table_name='autopilot_orders')
    op.drop_index(op.f('idx_autopilot_orders_strategy'), table_name='autopilot_orders')
    op.drop_index(op.f('idx_autopilot_orders_trading_mode'), table_name='autopilot_orders')
    op.drop_index(op.f('idx_autopilot_orders_user'), table_name='autopilot_orders')
    op.drop_index(op.f('idx_autopilot_orders_user_date'), table_name='autopilot_orders')
    op.drop_index(op.f('idx_confirmations_created'), table_name='autopilot_pending_confirmations')
    op.drop_index(op.f('idx_confirmations_expires'), table_name='autopilot_pending_confirmations', postgresql_where="(status = 'pending'::autopilot_confirmation_status)")
    op.drop_index(op.f('idx_confirmations_pending'), table_name='autopilot_pending_confirmations', postgresql_where="(status = 'pending'::autopilot_confirmation_status)")
    op.drop_index(op.f('idx_confirmations_status'), table_name='autopilot_pending_confirmations')
    op.drop_index(op.f('idx_confirmations_strategy'), table_name='autopilot_pending_confirmations')
    op.drop_index(op.f('idx_confirmations_user'), table_name='autopilot_pending_confirmations')
    op.drop_index(op.f('idx_reports_created'), table_name='autopilot_reports')
    op.drop_index(op.f('idx_reports_type'), table_name='autopilot_reports')
    op.drop_index(op.f('idx_reports_user'), table_name='autopilot_reports')
    op.alter_column('autopilot_strategies', 'staged_entry_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Configuration for staged entry (half-size or staggered mode)',
               existing_comment='Phase 5I: Configuration for staged entry (half-size or staggered mode).\n        Structure:\n        {\n            "enabled": true,\n            "mode": "half_size" | "staggered",\n            "initial_stage": {...},    // for half_size mode\n            "add_stage": {...},         // for half_size mode\n            "leg_entries": [...]        // for staggered mode\n        }',
               existing_nullable=True)
    op.alter_column('autopilot_strategies', 'net_gamma',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               type_=sa.Numeric(precision=8, scale=6),
               existing_nullable=True)
    op.alter_column('autopilot_strategies', 'net_vega',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=8, scale=4),
               existing_nullable=True)
    op.drop_index(op.f('idx_autopilot_strategies_active'), table_name='autopilot_strategies', postgresql_where="(status = ANY (ARRAY['waiting'::autopilot_strategy_status, 'active'::autopilot_strategy_status, 'pending'::autopilot_strategy_status]))")
    op.drop_index(op.f('idx_autopilot_strategies_created'), table_name='autopilot_strategies')
    op.drop_index(op.f('idx_autopilot_strategies_legs'), table_name='autopilot_strategies', postgresql_ops={'legs_config': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_autopilot_strategies_schedule'), table_name='autopilot_strategies', postgresql_ops={'schedule_config': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_autopilot_strategies_status'), table_name='autopilot_strategies')
    op.drop_index(op.f('idx_autopilot_strategies_trading_mode'), table_name='autopilot_strategies')
    op.drop_index(op.f('idx_autopilot_strategies_underlying'), table_name='autopilot_strategies')
    op.drop_index(op.f('idx_autopilot_strategies_user'), table_name='autopilot_strategies')
    op.drop_index(op.f('idx_autopilot_strategies_user_status'), table_name='autopilot_strategies')
    op.drop_index(op.f('idx_strategies_share_token'), table_name='autopilot_strategies', postgresql_where='(share_token IS NOT NULL)')
    op.drop_index(op.f('ix_autopilot_strategies_staged_entry'), table_name='autopilot_strategies', postgresql_where='(staged_entry_config IS NOT NULL)')
    op.drop_index(op.f('idx_template_ratings_template'), table_name='autopilot_template_ratings')
    op.drop_index(op.f('idx_template_ratings_user'), table_name='autopilot_template_ratings')
    op.drop_index(op.f('idx_autopilot_templates_category'), table_name='autopilot_templates', postgresql_where='(category IS NOT NULL)')
    op.drop_index(op.f('idx_autopilot_templates_public'), table_name='autopilot_templates', postgresql_where='(is_public = true)')
    op.drop_index(op.f('idx_autopilot_templates_tags'), table_name='autopilot_templates', postgresql_using='gin')
    op.drop_index(op.f('idx_autopilot_templates_user'), table_name='autopilot_templates', postgresql_where='(user_id IS NOT NULL)')
    op.drop_index(op.f('idx_templates_public'), table_name='autopilot_templates', postgresql_where='(is_public = true)')
    op.drop_index(op.f('idx_templates_system'), table_name='autopilot_templates', postgresql_where='(is_system = true)')
    op.drop_index(op.f('idx_trade_journal_entry_time'), table_name='autopilot_trade_journal')
    op.drop_index(op.f('idx_trade_journal_exit_reason'), table_name='autopilot_trade_journal')
    op.drop_index(op.f('idx_trade_journal_exit_time'), table_name='autopilot_trade_journal')
    op.drop_index(op.f('idx_trade_journal_open'), table_name='autopilot_trade_journal', postgresql_where='(is_open = true)')
    op.drop_index(op.f('idx_trade_journal_strategy'), table_name='autopilot_trade_journal')
    op.drop_index(op.f('idx_trade_journal_tags'), table_name='autopilot_trade_journal', postgresql_using='gin')
    op.drop_index(op.f('idx_trade_journal_underlying'), table_name='autopilot_trade_journal')
    op.drop_index(op.f('idx_trade_journal_user'), table_name='autopilot_trade_journal')
    op.drop_index(op.f('idx_trade_journal_user_entry'), table_name='autopilot_trade_journal')
    op.drop_index(op.f('idx_autopilot_user_settings_user'), table_name='autopilot_user_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_autopilot_user_settings_user'), 'autopilot_user_settings', ['user_id'], unique=False)
    op.create_index(op.f('idx_trade_journal_user_entry'), 'autopilot_trade_journal', ['user_id', sa.literal_column('entry_time DESC')], unique=False)
    op.create_index(op.f('idx_trade_journal_user'), 'autopilot_trade_journal', ['user_id'], unique=False)
    op.create_index(op.f('idx_trade_journal_underlying'), 'autopilot_trade_journal', ['underlying'], unique=False)
    op.create_index(op.f('idx_trade_journal_tags'), 'autopilot_trade_journal', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_trade_journal_strategy'), 'autopilot_trade_journal', ['strategy_id'], unique=False)
    op.create_index(op.f('idx_trade_journal_open'), 'autopilot_trade_journal', ['user_id', 'strategy_id'], unique=False, postgresql_where='(is_open = true)')
    op.create_index(op.f('idx_trade_journal_exit_time'), 'autopilot_trade_journal', [sa.literal_column('exit_time DESC')], unique=False)
    op.create_index(op.f('idx_trade_journal_exit_reason'), 'autopilot_trade_journal', ['exit_reason'], unique=False)
    op.create_index(op.f('idx_trade_journal_entry_time'), 'autopilot_trade_journal', [sa.literal_column('entry_time DESC')], unique=False)
    op.create_index(op.f('idx_templates_system'), 'autopilot_templates', ['category', 'name'], unique=False, postgresql_where='(is_system = true)')
    op.create_index(op.f('idx_templates_public'), 'autopilot_templates', ['category', sa.literal_column('avg_rating DESC'), sa.literal_column('usage_count DESC')], unique=False, postgresql_where='(is_public = true)')
    op.create_index(op.f('idx_autopilot_templates_user'), 'autopilot_templates', ['user_id'], unique=False, postgresql_where='(user_id IS NOT NULL)')
    op.create_index(op.f('idx_autopilot_templates_tags'), 'autopilot_templates', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_autopilot_templates_public'), 'autopilot_templates', ['is_public', 'usage_count'], unique=False, postgresql_where='(is_public = true)')
    op.create_index(op.f('idx_autopilot_templates_category'), 'autopilot_templates', ['category'], unique=False, postgresql_where='(category IS NOT NULL)')
    op.create_index(op.f('idx_template_ratings_user'), 'autopilot_template_ratings', ['user_id'], unique=False)
    op.create_index(op.f('idx_template_ratings_template'), 'autopilot_template_ratings', ['template_id'], unique=False)
    op.create_index(op.f('ix_autopilot_strategies_staged_entry'), 'autopilot_strategies', ['status'], unique=False, postgresql_where='(staged_entry_config IS NOT NULL)')
    op.create_index(op.f('idx_strategies_share_token'), 'autopilot_strategies', ['share_token'], unique=True, postgresql_where='(share_token IS NOT NULL)')
    op.create_index(op.f('idx_autopilot_strategies_user_status'), 'autopilot_strategies', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_autopilot_strategies_user'), 'autopilot_strategies', ['user_id'], unique=False)
    op.create_index(op.f('idx_autopilot_strategies_underlying'), 'autopilot_strategies', ['underlying'], unique=False)
    op.create_index(op.f('idx_autopilot_strategies_trading_mode'), 'autopilot_strategies', ['trading_mode'], unique=False)
    op.create_index(op.f('idx_autopilot_strategies_status'), 'autopilot_strategies', ['status'], unique=False)
    op.create_index(op.f('idx_autopilot_strategies_schedule'), 'autopilot_strategies', ['schedule_config'], unique=False, postgresql_ops={'schedule_config': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_autopilot_strategies_legs'), 'autopilot_strategies', ['legs_config'], unique=False, postgresql_ops={'legs_config': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_autopilot_strategies_created'), 'autopilot_strategies', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_autopilot_strategies_active'), 'autopilot_strategies', ['user_id', 'priority'], unique=False, postgresql_where="(status = ANY (ARRAY['waiting'::autopilot_strategy_status, 'active'::autopilot_strategy_status, 'pending'::autopilot_strategy_status]))")
    op.alter_column('autopilot_strategies', 'net_vega',
               existing_type=sa.Numeric(precision=8, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('autopilot_strategies', 'net_gamma',
               existing_type=sa.Numeric(precision=8, scale=6),
               type_=sa.NUMERIC(precision=6, scale=4),
               existing_nullable=True)
    op.alter_column('autopilot_strategies', 'staged_entry_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Phase 5I: Configuration for staged entry (half-size or staggered mode).\n        Structure:\n        {\n            "enabled": true,\n            "mode": "half_size" | "staggered",\n            "initial_stage": {...},    // for half_size mode\n            "add_stage": {...},         // for half_size mode\n            "leg_entries": [...]        // for staggered mode\n        }',
               existing_comment='Configuration for staged entry (half-size or staggered mode)',
               existing_nullable=True)
    op.create_index(op.f('idx_reports_user'), 'autopilot_reports', ['user_id'], unique=False)
    op.create_index(op.f('idx_reports_type'), 'autopilot_reports', ['user_id', 'report_type'], unique=False)
    op.create_index(op.f('idx_reports_created'), 'autopilot_reports', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_confirmations_user'), 'autopilot_pending_confirmations', ['user_id'], unique=False)
    op.create_index(op.f('idx_confirmations_strategy'), 'autopilot_pending_confirmations', ['strategy_id'], unique=False)
    op.create_index(op.f('idx_confirmations_status'), 'autopilot_pending_confirmations', ['status'], unique=False)
    op.create_index(op.f('idx_confirmations_pending'), 'autopilot_pending_confirmations', ['user_id', 'strategy_id', 'expires_at'], unique=False, postgresql_where="(status = 'pending'::autopilot_confirmation_status)")
    op.create_index(op.f('idx_confirmations_expires'), 'autopilot_pending_confirmations', ['expires_at'], unique=False, postgresql_where="(status = 'pending'::autopilot_confirmation_status)")
    op.create_index(op.f('idx_confirmations_created'), 'autopilot_pending_confirmations', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_autopilot_orders_user_date'), 'autopilot_orders', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_autopilot_orders_user'), 'autopilot_orders', ['user_id'], unique=False)
    op.create_index(op.f('idx_autopilot_orders_trading_mode'), 'autopilot_orders', ['trading_mode'], unique=False)
    op.create_index(op.f('idx_autopilot_orders_strategy'), 'autopilot_orders', ['strategy_id'], unique=False)
    op.create_index(op.f('idx_autopilot_orders_status'), 'autopilot_orders', ['status'], unique=False)
    op.create_index(op.f('idx_autopilot_orders_pending'), 'autopilot_orders', ['strategy_id', 'created_at'], unique=False, postgresql_where="(status = ANY (ARRAY['pending'::autopilot_order_status, 'placed'::autopilot_order_status, 'open'::autopilot_order_status]))")
    op.create_index(op.f('idx_autopilot_orders_kite'), 'autopilot_orders', ['kite_order_id'], unique=False, postgresql_where='(kite_order_id IS NOT NULL)')
    op.create_index(op.f('idx_autopilot_orders_created'), 'autopilot_orders', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_autopilot_orders_batch_id'), 'autopilot_orders', ['batch_id'], unique=False)
    op.create_index(op.f('idx_order_batches_user'), 'autopilot_order_batches', ['user_id'], unique=False)
    op.create_index(op.f('idx_order_batches_trading_mode'), 'autopilot_order_batches', ['trading_mode'], unique=False)
    op.create_index(op.f('idx_order_batches_strategy'), 'autopilot_order_batches', ['strategy_id'], unique=False)
    op.create_index(op.f('idx_order_batches_created'), 'autopilot_order_batches', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_autopilot_logs_user_created'), 'autopilot_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_autopilot_logs_user'), 'autopilot_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_autopilot_logs_strategy'), 'autopilot_logs', ['strategy_id'], unique=False, postgresql_where='(strategy_id IS NOT NULL)')
    op.create_index(op.f('idx_autopilot_logs_severity'), 'autopilot_logs', ['severity'], unique=False, postgresql_where="(severity = ANY (ARRAY['error'::autopilot_log_severity, 'critical'::autopilot_log_severity]))")
    op.create_index(op.f('idx_autopilot_logs_recent'), 'autopilot_logs', ['user_id', 'strategy_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_autopilot_logs_event'), 'autopilot_logs', ['event_type'], unique=False)
    op.create_index(op.f('idx_autopilot_logs_data'), 'autopilot_logs', ['event_data'], unique=False, postgresql_ops={'event_data': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_autopilot_logs_created'), 'autopilot_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_autopilot_daily_summary_user_date'), 'autopilot_daily_summary', ['user_id', sa.literal_column('summary_date DESC')], unique=False)
    op.create_index(op.f('idx_autopilot_daily_summary_user'), 'autopilot_daily_summary', ['user_id'], unique=False)
    op.create_index(op.f('idx_autopilot_daily_summary_date'), 'autopilot_daily_summary', [sa.literal_column('summary_date DESC')], unique=False)
    op.create_index(op.f('idx_autopilot_condition_eval_time'), 'autopilot_condition_eval', [sa.literal_column('evaluated_at DESC')], unique=False)
    op.create_index(op.f('idx_autopilot_condition_eval_strategy'), 'autopilot_condition_eval', ['strategy_id'], unique=False)
    op.create_index(op.f('idx_autopilot_condition_eval_latest'), 'autopilot_condition_eval', ['strategy_id', 'condition_type', 'condition_index', sa.literal_column('evaluated_at DESC')], unique=False)
    op.create_index(op.f('idx_backtests_user'), 'autopilot_backtests', ['user_id'], unique=False)
    op.create_index(op.f('idx_backtests_status'), 'autopilot_backtests', ['user_id', 'status'], unique=False)
    op.create_index(op.f('idx_backtests_created'), 'autopilot_backtests', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_analytics_cache_valid'), 'autopilot_analytics_cache', ['user_id', 'is_valid', 'expires_at'], unique=False)
    op.create_index(op.f('idx_analytics_cache_user'), 'autopilot_analytics_cache', ['user_id'], unique=False)
    op.create_index(op.f('idx_analytics_cache_key'), 'autopilot_analytics_cache', ['user_id', 'cache_key'], unique=False)
    op.alter_column('autopilot_adjustment_suggestions', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='Adjustment category: defensive (reduces risk), offensive (increases risk for premium), neutral (rebalances)',
               existing_server_default=sa.text("'defensive'::character varying"))
    op.create_index(op.f('idx_adjustment_logs_user'), 'autopilot_adjustment_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_adjustment_logs_triggered'), 'autopilot_adjustment_logs', [sa.literal_column('triggered_at DESC')], unique=False)
    op.create_index(op.f('idx_adjustment_logs_strategy'), 'autopilot_adjustment_logs', ['strategy_id'], unique=False)
    op.create_index(op.f('idx_adjustment_logs_rule'), 'autopilot_adjustment_logs', ['rule_id'], unique=False)
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
