"""add_drawdown_aware_position_sizing_to_ai_user_config

Revision ID: e07c3e092d27
Revises: 665b6deade94
Create Date: 2025-12-26 15:08:18.099368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e07c3e092d27'
down_revision: Union[str, Sequence[str], None] = '665b6deade94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ai_decisions_strategy'), table_name='ai_decisions_log', if_exists=True)
    op.drop_index(op.f('idx_ai_decisions_type'), table_name='ai_decisions_log', if_exists=True)
    op.drop_index(op.f('idx_ai_decisions_user_time'), table_name='ai_decisions_log', if_exists=True)
    op.drop_table('ai_decisions_log', if_exists=True)
    op.drop_index(op.f('idx_ai_market_snapshots_regime'), table_name='ai_market_snapshots', if_exists=True)
    op.drop_index(op.f('idx_ai_market_snapshots_time'), table_name='ai_market_snapshots', if_exists=True)
    op.drop_index(op.f('idx_ai_market_snapshots_underlying'), table_name='ai_market_snapshots', if_exists=True)
    op.drop_table('ai_market_snapshots', if_exists=True)
    op.drop_index(op.f('ix_ai_learning_reports_report_date'), table_name='ai_learning_reports', if_exists=True)
    op.drop_index(op.f('ix_ai_learning_reports_user_id'), table_name='ai_learning_reports', if_exists=True)
    op.drop_index(op.f('ix_ai_learning_reports_user_id_report_date'), table_name='ai_learning_reports', if_exists=True)
    op.drop_index(op.f('ix_ai_model_registry_is_active'), table_name='ai_model_registry', if_exists=True)

    # Add columns as nullable first
    op.add_column('ai_user_config', sa.Column('enable_drawdown_sizing', sa.Boolean(), nullable=True))
    op.add_column('ai_user_config', sa.Column('drawdown_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_user_config', sa.Column('enable_volatility_sizing', sa.Boolean(), nullable=True))
    op.add_column('ai_user_config', sa.Column('volatility_lookback_days', sa.Integer(), nullable=True))
    op.add_column('ai_user_config', sa.Column('volatility_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('ai_user_config', sa.Column('max_drawdown_to_trade', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('ai_user_config', sa.Column('high_water_mark', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('ai_user_config', sa.Column('current_drawdown_pct', sa.Numeric(precision=5, scale=2), nullable=True))

    # Update existing rows with default values
    op.execute("""
        UPDATE ai_user_config
        SET
            enable_drawdown_sizing = FALSE,
            drawdown_thresholds = '[
                {"level": "NORMAL", "min_dd": 0.0, "max_dd": 5.0, "multiplier": 1.0},
                {"level": "CAUTION", "min_dd": 5.0, "max_dd": 10.0, "multiplier": 0.8},
                {"level": "WARNING", "min_dd": 10.0, "max_dd": 15.0, "multiplier": 0.6},
                {"level": "CRITICAL", "min_dd": 15.0, "max_dd": 20.0, "multiplier": 0.4},
                {"level": "SEVERE", "min_dd": 20.0, "max_dd": 100.0, "multiplier": 0.2}
            ]'::jsonb,
            enable_volatility_sizing = FALSE,
            volatility_lookback_days = 30,
            volatility_thresholds = '[
                {"level": "LOW", "max_volatility": 5000.0, "multiplier": 1.0},
                {"level": "MEDIUM", "max_volatility": 10000.0, "multiplier": 0.8},
                {"level": "HIGH", "max_volatility": 999999.0, "multiplier": 0.6}
            ]'::jsonb,
            max_drawdown_to_trade = 25.00,
            current_drawdown_pct = 0.00
        WHERE
            enable_drawdown_sizing IS NULL
    """)

    # Now alter columns to NOT NULL (except high_water_mark which stays nullable)
    op.alter_column('ai_user_config', 'enable_drawdown_sizing', nullable=False)
    op.alter_column('ai_user_config', 'drawdown_thresholds', nullable=False)
    op.alter_column('ai_user_config', 'enable_volatility_sizing', nullable=False)
    op.alter_column('ai_user_config', 'volatility_lookback_days', nullable=False)
    op.alter_column('ai_user_config', 'volatility_thresholds', nullable=False)
    op.alter_column('ai_user_config', 'max_drawdown_to_trade', nullable=False)
    op.alter_column('ai_user_config', 'current_drawdown_pct', nullable=False)

    # Add CHECK constraints
    op.create_check_constraint(
        'chk_max_drawdown_to_trade_range',
        'ai_user_config',
        'max_drawdown_to_trade >= 0 AND max_drawdown_to_trade <= 100'
    )
    op.create_check_constraint(
        'chk_current_drawdown_pct_range',
        'ai_user_config',
        'current_drawdown_pct >= 0 AND current_drawdown_pct <= 100'
    )
    op.create_check_constraint(
        'chk_volatility_lookback_days_positive',
        'ai_user_config',
        'volatility_lookback_days > 0'
    )

    op.drop_index(op.f('idx_ai_user_config_enabled'), table_name='ai_user_config', if_exists=True)
    op.drop_index(op.f('idx_ai_user_config_user_id'), table_name='ai_user_config', if_exists=True)
    op.drop_index(op.f('idx_autopilot_strategies_ai_confidence'), table_name='autopilot_strategies', if_exists=True)
    op.drop_index(op.f('idx_autopilot_strategies_ai_deployed'), table_name='autopilot_strategies', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_autopilot_strategies_ai_deployed'), 'autopilot_strategies', ['ai_deployed', 'user_id'], unique=False)
    op.create_index(op.f('idx_autopilot_strategies_ai_confidence'), 'autopilot_strategies', ['ai_confidence_score'], unique=False)
    op.create_index(op.f('idx_ai_user_config_user_id'), 'ai_user_config', ['user_id'], unique=True)
    op.create_index(op.f('idx_ai_user_config_enabled'), 'ai_user_config', ['ai_enabled'], unique=False)
    op.drop_column('ai_user_config', 'current_drawdown_pct')
    op.drop_column('ai_user_config', 'high_water_mark')
    op.drop_column('ai_user_config', 'max_drawdown_to_trade')
    op.drop_column('ai_user_config', 'volatility_thresholds')
    op.drop_column('ai_user_config', 'volatility_lookback_days')
    op.drop_column('ai_user_config', 'enable_volatility_sizing')
    op.drop_column('ai_user_config', 'drawdown_thresholds')
    op.drop_column('ai_user_config', 'enable_drawdown_sizing')
    op.create_index(op.f('ix_ai_model_registry_is_active'), 'ai_model_registry', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_learning_reports_user_id_report_date'), 'ai_learning_reports', ['user_id', 'report_date'], unique=False)
    op.create_index(op.f('ix_ai_learning_reports_user_id'), 'ai_learning_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_learning_reports_report_date'), 'ai_learning_reports', ['report_date'], unique=False)
    op.create_table('ai_market_snapshots',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('snapshot_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('underlying', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('regime_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('spot_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('vix', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('rsi_14', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('adx_14', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('ema_9', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('ema_21', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('ema_50', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('atr_14', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('bb_upper', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('bb_lower', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('bb_width_pct', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('oi_pcr', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('max_pain', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('confidence >= 0::numeric AND confidence <= 100::numeric', name=op.f('chk_confidence_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_market_snapshots_pkey'))
    )
    op.create_index(op.f('idx_ai_market_snapshots_underlying'), 'ai_market_snapshots', ['underlying', sa.literal_column('snapshot_time DESC')], unique=False)
    op.create_index(op.f('idx_ai_market_snapshots_time'), 'ai_market_snapshots', [sa.literal_column('snapshot_time DESC')], unique=False)
    op.create_index(op.f('idx_ai_market_snapshots_regime'), 'ai_market_snapshots', ['regime_type'], unique=False)
    op.create_table('ai_decisions_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('strategy_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('decision_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('action_taken', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('regime_at_decision', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('vix_at_decision', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('spot_at_decision', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('indicators_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('outcome_pnl', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
    sa.Column('outcome_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('was_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('decision_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('outcome_recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['autopilot_strategies.id'], name=op.f('ai_decisions_log_strategy_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ai_decisions_log_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_decisions_log_pkey'))
    )
    op.create_index(op.f('idx_ai_decisions_user_time'), 'ai_decisions_log', ['user_id', 'decision_time'], unique=False)
    op.create_index(op.f('idx_ai_decisions_type'), 'ai_decisions_log', ['decision_type'], unique=False)
    op.create_index(op.f('idx_ai_decisions_strategy'), 'ai_decisions_log', ['strategy_id'], unique=False)
    # ### end Alembic commands ###
