"""add eod_option_snapshots table

Revision ID: e33bac2d22ae
Revises: c14bb31eee95
Create Date: 2026-04-12 19:59:08.094751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e33bac2d22ae'
down_revision: Union[str, Sequence[str], None] = 'c14bb31eee95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eod_option_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('underlying', sa.String(length=20), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('strike', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('ce_ltp', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('ce_oi', sa.BigInteger(), nullable=True),
    sa.Column('ce_volume', sa.BigInteger(), nullable=True),
    sa.Column('ce_iv', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('pe_ltp', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('pe_oi', sa.BigInteger(), nullable=True),
    sa.Column('pe_volume', sa.BigInteger(), nullable=True),
    sa.Column('pe_iv', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('spot_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('underlying', 'expiry_date', 'strike', name='uq_eod_snapshot_strike')
    )
    op.create_index('idx_eod_snapshot_lookup', 'eod_option_snapshots', ['underlying', 'expiry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_eod_snapshot_lookup', table_name='eod_option_snapshots')
    op.drop_table('eod_option_snapshots')
    # ### end Alembic commands ###
