"""add_regime_drift_detection_to_ai_module

Revision ID: eba6d4e94406
Revises: e07c3e092d27
Create Date: 2025-12-26 15:18:02.444485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eba6d4e94406'
down_revision: Union[str, Sequence[str], None] = 'e07c3e092d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_regime_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('underlying', sa.String(length=20), nullable=False),
    sa.Column('regime_type', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Technical indicators at classification time'),
    sa.Column('reasoning', sa.String(length=500), nullable=True, comment='Why this regime was selected'),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('was_drift', sa.Numeric(precision=3, scale=2), nullable=True, comment='Drift score at this point (0-1, computed post-facto)'),
    sa.Column('regime_changed', sa.String(length=1), nullable=True, comment='Y if regime changed from previous, N otherwise'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regime_history_drift_lookup', 'ai_regime_history', ['underlying', 'classified_at', 'regime_type'], unique=False)
    op.create_index('idx_regime_history_underlying_time', 'ai_regime_history', ['underlying', 'classified_at'], unique=False, postgresql_using='btree')
    op.create_index(op.f('ix_ai_regime_history_classified_at'), 'ai_regime_history', ['classified_at'], unique=False)
    op.create_index(op.f('ix_ai_regime_history_regime_type'), 'ai_regime_history', ['regime_type'], unique=False)
    op.create_index(op.f('ix_ai_regime_history_underlying'), 'ai_regime_history', ['underlying'], unique=False)
    # Add columns as nullable first
    op.add_column('ai_user_config', sa.Column('enable_drift_detection', sa.Boolean(), nullable=True))
    op.add_column('ai_user_config', sa.Column('drift_lookback_periods', sa.Integer(), nullable=True))
    op.add_column('ai_user_config', sa.Column('drift_threshold', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('ai_user_config', sa.Column('drift_confidence_penalty', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('ai_user_config', sa.Column('min_regime_stability_score', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('ai_user_config', sa.Column('current_regime_stability', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('ai_user_config', sa.Column('last_drift_check_at', sa.DateTime(timezone=True), nullable=True))

    # Update existing rows with default values
    op.execute("""
        UPDATE ai_user_config
        SET
            enable_drift_detection = TRUE,
            drift_lookback_periods = 20,
            drift_threshold = 30.00,
            drift_confidence_penalty = 10.00,
            min_regime_stability_score = 40.00,
            current_regime_stability = 100.00
        WHERE
            enable_drift_detection IS NULL
    """)

    # Now alter columns to NOT NULL (except last_drift_check_at which stays nullable)
    op.alter_column('ai_user_config', 'enable_drift_detection', nullable=False)
    op.alter_column('ai_user_config', 'drift_lookback_periods', nullable=False)
    op.alter_column('ai_user_config', 'drift_threshold', nullable=False)
    op.alter_column('ai_user_config', 'drift_confidence_penalty', nullable=False)
    op.alter_column('ai_user_config', 'min_regime_stability_score', nullable=False)
    op.alter_column('ai_user_config', 'current_regime_stability', nullable=False)

    # Add CHECK constraints
    op.create_check_constraint(
        'chk_drift_lookback_periods_positive',
        'ai_user_config',
        'drift_lookback_periods > 0'
    )
    op.create_check_constraint(
        'chk_drift_threshold_range',
        'ai_user_config',
        'drift_threshold >= 0 AND drift_threshold <= 100'
    )
    op.create_check_constraint(
        'chk_drift_confidence_penalty_range',
        'ai_user_config',
        'drift_confidence_penalty >= 0 AND drift_confidence_penalty <= 100'
    )
    op.create_check_constraint(
        'chk_min_regime_stability_score_range',
        'ai_user_config',
        'min_regime_stability_score >= 0 AND min_regime_stability_score <= 100'
    )
    op.create_check_constraint(
        'chk_current_regime_stability_range',
        'ai_user_config',
        'current_regime_stability >= 0 AND current_regime_stability <= 100'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_user_config', 'last_drift_check_at')
    op.drop_column('ai_user_config', 'current_regime_stability')
    op.drop_column('ai_user_config', 'min_regime_stability_score')
    op.drop_column('ai_user_config', 'drift_confidence_penalty')
    op.drop_column('ai_user_config', 'drift_threshold')
    op.drop_column('ai_user_config', 'drift_lookback_periods')
    op.drop_column('ai_user_config', 'enable_drift_detection')
    op.drop_index(op.f('ix_ai_regime_history_underlying'), table_name='ai_regime_history')
    op.drop_index(op.f('ix_ai_regime_history_regime_type'), table_name='ai_regime_history')
    op.drop_index(op.f('ix_ai_regime_history_classified_at'), table_name='ai_regime_history')
    op.drop_index('idx_regime_history_underlying_time', table_name='ai_regime_history', postgresql_using='btree')
    op.drop_index('idx_regime_history_drift_lookup', table_name='ai_regime_history')
    op.drop_table('ai_regime_history')
    # ### end Alembic commands ###
