"""Add strategy_templates table

Revision ID: f006d85ae956
Revises: 5c93d8e7b231
Create Date: 2025-12-07 15:16:18.091643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f006d85ae956'
down_revision: Union[str, Sequence[str], None] = '5c93d8e7b231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('legs_config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('max_profit', sa.String(length=50), nullable=False),
    sa.Column('max_loss', sa.String(length=50), nullable=False),
    sa.Column('breakeven', sa.String(length=200), nullable=True),
    sa.Column('market_outlook', sa.String(length=50), nullable=False),
    sa.Column('volatility_preference', sa.String(length=50), nullable=False),
    sa.Column('ideal_iv_rank', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('capital_requirement', sa.String(length=20), nullable=False),
    sa.Column('margin_requirement', sa.String(length=50), nullable=True),
    sa.Column('theta_positive', sa.Boolean(), nullable=True),
    sa.Column('vega_positive', sa.Boolean(), nullable=True),
    sa.Column('delta_neutral', sa.Boolean(), nullable=True),
    sa.Column('gamma_risk', sa.String(length=20), nullable=True),
    sa.Column('win_probability', sa.String(length=50), nullable=True),
    sa.Column('profit_target', sa.String(length=100), nullable=True),
    sa.Column('when_to_use', sa.Text(), nullable=True),
    sa.Column('pros', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('cons', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('common_mistakes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('exit_rules', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('adjustments', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('example_underlying', sa.String(length=20), nullable=True),
    sa.Column('example_spot', sa.Float(), nullable=True),
    sa.Column('example_setup', sa.Text(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_templates_category'), 'strategy_templates', ['category'], unique=False)
    op.create_index(op.f('ix_strategy_templates_id'), 'strategy_templates', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_templates_name'), 'strategy_templates', ['name'], unique=True)
    op.drop_index(op.f('idx_strategies_share_code'), table_name='strategies')
    op.drop_index(op.f('idx_strategies_user'), table_name='strategies')
    op.create_index(op.f('ix_strategies_share_code'), 'strategies', ['share_code'], unique=True)
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.drop_index(op.f('idx_strategy_legs_strategy'), table_name='strategy_legs')
    op.create_index(op.f('ix_strategy_legs_strategy_id'), 'strategy_legs', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_legs_strategy_id'), table_name='strategy_legs')
    op.create_index(op.f('idx_strategy_legs_strategy'), 'strategy_legs', ['strategy_id'], unique=False)
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_share_code'), table_name='strategies')
    op.create_index(op.f('idx_strategies_user'), 'strategies', ['user_id'], unique=False)
    op.create_index(op.f('idx_strategies_share_code'), 'strategies', ['share_code'], unique=True)
    op.drop_index(op.f('ix_strategy_templates_name'), table_name='strategy_templates')
    op.drop_index(op.f('ix_strategy_templates_id'), table_name='strategy_templates')
    op.drop_index(op.f('ix_strategy_templates_category'), table_name='strategy_templates')
    op.drop_table('strategy_templates')
    # ### end Alembic commands ###
